### ISSUE TITLE
桌面客户端 Linux release

### ISSUE THREAD

**Issue by YidaozhanYa** [GuMengYu/music-you#15]

**Comment by gov360** [comment]
希望有appimage版本发布，这样我的Linuxmint就可以使用了

[appimage官网](https://appimage.org)

**Comment by GuMengYu** [comment]
暂时没有装Linux，所以没法儿测试，可以自己fork 尝试打一下 see [electron-builder](https://www.electron.build/configuration/linux)

**Comment by YidaozhanYa** [comment]
#24
