### ISSUE TITLE
迷你控制栏部分控件不应用主题色

### ISSUE THREAD

**Issue by 1818yu** [GuMengYu/music-you#18]
![music-you_9CuiLyrCVw](https://user-images.githubusercontent.com/56754498/205288164-78895f5f-1a83-45eb-985c-819069730746.gif)
↑底部控制栏

![music-you_hjFnG6023T](https://user-images.githubusercontent.com/56754498/205288243-407f4556-beb4-4936-860e-4e724e634d18.gif)
↑迷你控制栏

**随机播放**和**播放顺序**两个控件在两种控制栏中应用主题色的情况不一致，其他控件是一致的

希望统一下，最好都应用主题色🫡

**Comment by GuMengYu** [comment]
下个版本修正
