### ISSUE TITLE
vercel部署

### ISSUE THREAD

**Issue by lifeafter619** [GuMengYu/music-you#27]
**Describe the bug**
您好，我有vercel部署的需求，但是部署后是404，请问具体应该怎样部署？
我已经部署了可用的api
我的项目地址在 https://test2.66619.eu.org

**To Reproduce**
![image](https://user-images.githubusercontent.com/65111206/209780286-6a8a6ad5-7532-48b3-ad88-a9cf40260f41.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win
 - Version [e.g. v2.0.8]

**Comment by lifeafter619** [comment]
@GuMengYu

**Comment by GuMengYu** [comment]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/22021419/209783261-7f956fd3-a102-4de9-992e-97216ef89ab4.png">
检查 Output Directory

**Comment by lifeafter619** [comment]
谢谢您，现在显示了，但是它没有内容
我已经修改了vercel.json为我的api，部署在https://netease-api.66619.eu.org/
https://github.com/lifeafter619/music-you/blob/6a6bafb4eb85d5605ce2528ac1e36fa41426ad87/vercel.json#L5
![image](https://user-images.githubusercontent.com/65111206/209786304-2bdba062-58f3-45a9-a502-6d149aef58b4.png)
我的api也正常工作
![image](https://user-images.githubusercontent.com/65111206/209786381-0c9f2076-7616-42b8-b3a0-7069143c5fd2.png)
但是页面上没有内容，并报错
![image](https://user-images.githubusercontent.com/65111206/209786531-ff470e9d-1e1c-4ed2-96bb-43169eca6ecf.png)
请问这又是什么问题？

**Comment by GuMengYu** [comment]
503 可能ip被网易云限制了吧
