### ISSUE TITLE
托盘图标消失了

### ISSUE THREAD

**Issue by 1818yu** [GuMengYu/music-you#28]
**Describe the bug**
托盘图标消失了

**To Reproduce**

**Expected behavior**

**Screenshots**
![6AZWQHzGvG](https://user-images.githubusercontent.com/56754498/211247697-e75d491e-edb8-4d59-9818-cb0768761a6d.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [22621.963]

**Comment by GuMengYu** [comment]
临时版本可在actions里下载
https://github.com/GuMengYu/music-you/actions/runs/3893122736
