### ISSUE TITLE
邮箱、手机号登录无效

### ISSUE THREAD

**Issue by SoDebug** [GuMengYu/music-you#31]
**Describe the bug**
登录方式选中 邮箱|手机号登录 时无反应，点击登录键后会转圈，但是不会登录，也不会报错。
**To Reproduce**
1. 打开软件
2. 使用 邮箱|手机号登录 方式登录

**Expected behavior**
使用 邮箱|手机号登录 方式登录后要么登录成功，要么报错
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS] :Windows 11
 - Version [e.g. v2.0.8] :22623.1180

**Comment by GuMengYu** [comment]
好像是上游的接口问题
https://github.com/Binaryify/NeteaseCloudMusicApi/issues/1687
网易开启了网易易盾
先用扫码登录吧
