### ISSUE TITLE
播放界面的图片来自哪里啊

### ISSUE THREAD

**Issue by ke-xi** [GuMengYu/music-you#32]
![Snipaste_2023-03-13_16-57-05.png](https://image.baidu.com/search/down?url=https://tvax1.sinaimg.cn/large/005REQzJly1hbyc5aicppj31e20xkhdt.jpg)
感觉好好看,这些图片的来源地址是什么啊,缓存在哪里啊,可以在我的电脑里找到吗

**Comment by GuMengYu** [comment]
来自 wallhaven 这个网站的api

可惜公主爱王子 ***@***.***> 于 2023年3月13日周一 17:00写道：
