### ISSUE TITLE
可以播放本地音乐嘛

### ISSUE THREAD

**Issue by winlee-d** [GuMengYu/music-you#36]
为啥大家都热衷于开发三方网易云，明明都做得很好，没一个支持播放本地音乐的，emoji，网上找了一大圈就一个musicplayer2好用一点，不过界面不是很好看，这个项目的节目我都要舔屏了。

**Comment by GuMengYu** [comment]
有计划
但自己本地音乐用的不多，所以没太多时间来开发

**Comment by GuMengYu** [comment]
新版支持了本地音乐播放
