### ISSUE TITLE
添加独立的关闭，最小化，最大化

### ISSUE THREAD

**Issue by BlueSword03** [GuMengYu/music-you#39]
**Describe the bug**

**To Reproduce**
1. 打开客户端

**Expected behavior**
应当具有独立的关闭，最小化，最大化

**Screenshots**
![image](https://github.com/GuMengYu/music-you/assets/62334979/6c504dc1-f763-4b3b-ad3d-3b09f676447c)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04.2   , Gnome 42.9]
 - Version [e.g. v2.0.12]

**Comment by GuMengYu** [comment]
Windows 给漏了 现在最新提交加了 但没发release
