### ISSUE TITLE
1个优化和bug

### ISSUE THREAD

**Issue by myloveht88** [GuMengYu/music-you#44]
菜单按钮和操作按钮重叠
![image](https://github.com/GuMengYu/music-you/assets/86819778/5e927f71-c902-4aff-bb2a-d086942a518a)
歌词页面报错：
![image](https://github.com/GuMengYu/music-you/assets/86819778/7eb59111-f1ae-4e0b-ac55-d6b5837f113a)
歌词设置页面报错
![image](https://github.com/GuMengYu/music-you/assets/86819778/18196fb2-977a-43d6-aa4e-24dc49471223)

**Comment by GuMengYu** [comment]
歌词设置页面报错
-- 这个wallpaper 接入的wallhaven 的要开代理，后面考虑默认关掉

**Comment by GuMengYu** [comment]
5dd88c67f339e1e23feec7366b8433d4c0094d8c
