### ISSUE TITLE
请问大佬，npm run dev启动web端报__dirname的错，如何解决呢

### ISSUE THREAD

**Issue by Jxingyu** [GuMengYu/music-you#46]
控制台error如下
![image](https://github.com/GuMengYu/music-you/assets/70691310/827f4acc-0451-450b-ab91-ee0685bade4f)

**Comment by GuMengYu** [comment]
web 用 dev分支 （功能不是很新）

有些功能桌面客户端才有

**Comment by Jxingyu** [comment]
请问大佬，web启动后在浏览器是空白页面怎么解决呢

**Comment by GuMengYu** [comment]
🤔️可能还是一样的问题 web 分支里 electron的代码没清理干净，你可以试着找下 electron

Jxingyu ***@***.***>于2023年9月30日 周六11:42写道：
